# Generated by Django 5.2.10 on 2026-06-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EV_chain_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charging_center',
            old_name='centre_name',
            new_name='center_name',
        ),
    ]
