# Generated by Django 5.2.10 on 2026-06-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV_chain_app', '0002_rename_centre_name_charging_center_center_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='login',
        ),
        migrations.AddField(
            model_name='booking',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EV_chain_app.charging_center'),
            preserve_default=False,
        ),
    ]
