# Generated by Django 5.2.10 on 2026-06-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EV_chain_app', '0003_remove_booking_login_booking_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='login',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EV_chain_app.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='login',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EV_chain_app.login'),
            preserve_default=False,
        ),
    ]
